language: rust

sudo: true

git:
  depth: false

dist: bionic

matrix:
  include:
    - os: linux
      env:
        - CODECOV_COVERAGE=true
        - PUBLISH_DOC=true
        - PUBLISH_PACKAGE=true
      addons:
        apt:
          update: true
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
    - os: osx
    - os: windows
    - rust: beta
    - rust: nightly
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - FEATURES=--features=vendored
      addons:
        apt:
          update: true
          packages: musl-tools
    - os: windows
      env: TARGET=x86_64-pc-windows-gnu

before_install:
  - chmod -R 777 ci

install:
  - . ci/install.sh

before_script:
  - . ci/before_script.sh

script:
  - . ci/script.sh

deploy:
  - provider: script
    script: bash ci/create_index.sh
    skip-cleanup: true
    on:
      branch: master
      condition: $PUBLISH_DOC = true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: "target/doc"
    committer_from_gh: true
    on:
      branch: master
      condition: $PUBLISH_DOC = true
  - provider: cargo
    token: $CARGO_TOKEN
    on:
      tags: true
      condition: $PUBLISH_PACKAGE = true
  - provider: script
    script: bash ci/codecov_coverage.sh
    skip-cleanup: true
    on:
      all_branches: true
      condition: $CODECOV_COVERAGE = true

notifications:
  email: false