language: rust

rust:
  - stable
  - beta
  - nightly

sudo: true

git:
  depth: false
 
dist: xenial
  
os:
  - linux
  - osx
  - windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    fi

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

install:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      rustup component add rustfmt;
    fi
  - rustup component add clippy

before_script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      rustfmt -V;
    fi
  - cargo clippy -V

script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo fmt --verbose --all -- --check;
    fi
  - cargo clippy --verbose --all -- -D warnings
  - cargo build --verbose --all
  - cargo doc --no-deps --all
  - cargo test --verbose --all

deploy:
  - provider: script
    script: bash scripts/create_index.sh
    skip-cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable
  - provider: script
    script: bash scripts/codecov_coverage.sh
    skip-cleanup: true
    on:
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: "target/doc"
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable