language: rust

sudo: true

git:
  depth: false

dist: bionic

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
  - rust: beta
  - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    fi

install:
  - rustup component add rustfmt && RUSTFMT="yes" || RUSTFMT="no"
  - rustup component add clippy && CLIPPY="yes" || CLIPPY="no"

before_script:
  - if [[ "$RUSTFMT" == "yes" ]]; then
      rustfmt -V;
    fi
  - if [[ "$CLIPPY" == "yes" ]]; then
      cargo clippy -V;
    fi

script:
  - if [[ "$RUSTFMT" == "yes" ]]; then
      cargo fmt --all -- --check;
    fi
  - if [[ "$CLIPPY" == "yes" ]]; then
      cargo clippy --all -- -D warnings;
    fi
  - cargo build --all
  - cargo doc --no-deps --all
  - cargo test --all

before_deploy:
  - chmod +x scripts/codecov_coverage.sh

deploy:
  - provider: cargo
    token: $CARGO_TOKEN
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable
  - provider: script
    script: bash scripts/codecov_coverage.sh
    skip-cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable