[package]
name = "alpha_vantage"
version = "0.1.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
edition = "2018"

[dependencies]
reqwest="0.9.2"
serde="1.0.79"
serde_json="1.0.32"
serde_derive="1.0.79"
