[package]
name = "alpha_vantage"
version = "0.1.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
edition = "2018"
description="Rust Wrapper/Crate built for AlphaVantage API"
license="MIT"

[dependencies]
reqwest="0.9.10"
serde="1.0.89"
serde_json="1.0.39"
serde_derive="1.0.89"
