[package]
name = "alpha_vantage"
version = "0.4.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/alpha_vantage"
repository = "https://github.com/iamsauravsharma/alpha_vantage"
description="Rust Wrapper/Crate built for AlphaVantage API"
license="MIT"
readme = "README.MD"
edition = "2018"
keywords = ["alphavantage","currency","finance","stock","exchange"]
categories = ["api-bindings","web-programming::http-client"]

[dependencies]
reqwest = {version = "0.10.4"}
serde = {version = "1.0.107", features = ["derive"]}
serde_json = "1.0.52"
thiserror = "1.0.16"


[dev-dependencies]
tokio = {version = "0.2.20", features = ["macros"]}

[features]
vendored = ["reqwest/native-tls-vendored"]
