[package]
name = "alpha_vantage"
version = "0.1.0"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
edition = "2018"
description="Rust Wrapper/Crate built for AlphaVantage API"
license="MIT"

[dependencies]
reqwest="0.9.6"
serde="1.0.84"
serde_json="1.0.34"
serde_derive="1.0.84"
