name: Shell Check
on: [pull_request]

jobs:
  shell-check:
    name: Shell Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}