name: Shellcheck scripts
on: [pull_request]

jobs:
  shell-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ShellCheck scripts
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
